---
- name: Bootstrap a new server
  hosts: all:!localhost
  sudo: yes
  gather_facts: yes
  vars_files:
    - vars/users.yml
    - vars/ejson_key.yml
    - roles/koodiklinikka.fi/defaults/main.yml
    - roles/koodiklinikka.fi-api/defaults/main.yml
  roles:
    - base
    - docker
    - nginx
    - newrelic_container
  tasks:
    - include: tasks/webuser.yml
