---
- name: Deploy tohtori
  hosts: application
  tasks:
    - { include: roles/deploy/tasks/deploy.yml, 
        container_name: tohtori, 
        repository_url: 'git@github.com:koodiklinikka/tohtori.git',
        port: 6666, 
        app_path: /opt/tohtori/tohtori,
        user: web }


