---
- name: Deploy api
  hosts: application
  tasks:
    - { include: roles/deploy/tasks/deploy.yml, 
        container_name: koodiklinikka.fi-api, 
        repository_url: 'git@github.com:koodiklinikka/koodiklinikka.fi-api.git',
        port: 9000, 
        app_path: /opt/web/koodiklinikka.fi-api,
        user: web }


