---
- name: Deploy front
  hosts: application
  tasks:
    - { include: roles/deploy/tasks/deploy.yml, 
        container_name: koodiklinikka.fi-front, 
        repository_url: 'git@github.com:koodiklinikka/koodiklinikka.fi.git',
        port: 8000, 
        app_path: /opt/web/koodiklinikka.fi-front,
        user: web }


