---

- name: get running container
  shell: docker ps -a|grep {{ koodiklinikka_tohtori_container_name }}|grep latest| awk '{print $1}'
  register: current_container_id

- name: kill old version
  shell: docker stop {{ koodiklinikka_tohtori_container_name }}
  when: current_container_id != ""

- name: get old containers
  shell: docker ps -a|grep Exited| awk '{print $1}'
  register: old_containers

- name: clean old containers
  shell: docker rm $(docker ps -a|grep Exited| awk '{print $1}')
  when: old_containers.stdout != ""

- name: Start the container
  shell: docker run -d --name {{ koodiklinikka_tohtori_container_name }} {{ koodiklinikka_tohtori_container_name }}:old

